workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      groups:
        - google_play
    scripts:
      - name: Build Android App Bundle
        script: |
          # Proje dosyalarının olduğu doğru klasörü bulup içine girelim
          cd $(find . -maxdepth 2 -name "gradlew" -exec dirname {} \; | head -n 1)
          
          # Bulunduğumuz yerde key.properties dosyasını oluşturalım
          mkdir -p app
          rm -f app/key.properties
          echo "storePassword=12531253" > app/key.properties
          echo "keyPassword=12531253" >> app/key.properties
          echo "keyAlias=my-key-alias" >> app/key.properties
          echo "storeFile=../release.keystore" >> app/key.properties
          
          # Yetkiyi verip build alalım
          chmod +x gradlew
          ./gradlew bundleRelease
    artifacts:
      - "**/app/build/outputs/bundle/release/app-release.aab"
